### ISSUE TITLE
Command line argument to specify config file

### ISSUE THREAD

**Issue by jakirkham** [PyCQA/pydocstyle#117]
It would be nice to be able to select a config file via a command argument. A feature like this exists for pep8 so something similar would be nice.

**Comment by Nurdok** [comment]
This seems reasonable. Pull Requests are welcome :)

**Comment by milkey-mouse** [comment]
I've done this on my fork. Just give me until Oct 1 😀

**Comment by lqaz** [comment]
@milkey-mouse Reminder to merge.
