### ISSUE TITLE
path to file is lowercased

### ISSUE THREAD

**Issue by BrnoPCmaniak** [PyCQA/pydocstyle#179]
When I enter full path to file in output the path is lowecased. This leads to errors in for example atom-pydocstyle because it opens files which don't exists.
```
[fdobrovolny@minos sis]$ pydocstyle /home/fdobrovolny/DEV/sis/.../function_based.py
/home/fdobrovolny/dev/sis/.../function_based.py:12 in public function `paginate`:
        D400: First line should end with a period (not 's')
```
(...=path is shortened)
```
[fdobrovolny@minos sis]$ pydocstyle --version
1.0.0
```

**Comment by Nurdok** [comment]
Thanks for reporting this, I'll try to get on it as soon as I can, but it will probably take me a few days.
Also, I didn't know about linter-pydocstyle. Awesome!

**Comment by sigmavirus24** [comment]
From what I can tell, pydocstyle opens the file without changing the casing. I think pydocstyle is just lower-casing the path when it prints it though. Is *that* what is causing problems for atom-pydocstyle?

**Comment by BrnoPCmaniak** [comment]
@sigmavirus24 yes, excatly that's the problem.

**Comment by sigmavirus24** [comment]
I've submitted #181 which I *think* fixes this. Please try it out @BrnoPCmaniak (you may also need PR #180 for it to work though).

**Comment by BrnoPCmaniak** [comment]
@sigmavirus24 works 100% thanks a lot.

**Comment by sigmavirus24** [comment]
I think @Nurdok might want to leave this open until that's merged. Thanks for confirming though @BrnoPCmaniak
