### ISSUE TITLE
Wrapped docstrings?

### ISSUE THREAD

**Issue by jackwilsdon** [PyCQA/pydocstyle#184]
Is it possible for pydocstyle to support wrapped docstrings?

My issue is that I'm trying to follow both PEP 8 and PEP 257, but I'm having a hard time doing so due to the fact that pydocstyle requires summary lines to end with a full stop and they cannot be wrapped (as well as a few other checks mentioned below).

The issue seems to manifest itself in a few checks:

```python
# D200: One-line docstring should fit on one line with quotes (found 2)
#
# Reasoning: The quotes need to be wrapped to fit to 79 characters.

    def test_remove_filter(self):
        """Test whether or not filters removed with remove_filter are removed.
        """
```

```python
# D205: 1 blank line required between summary line and description (found 0)
# D208: Docstring is over-indented
# D400: First line should end with a period (not 'd')
#
# Reasoning: The summary line needs to be wrapped to fit to 79 characters.

    def test_execute_callback_args(self):
        """Test whether or not the callback is called with the expected
           arguments.
        """
```

What is the best way to go about sorting this out?

I know I could disable the rules/checks but it doesn't really feel like a good way of doing it.

**Comment by Nurdok** [comment]
What is PEP8 is making you use wrapped docstring? The simple solution is to rephrase the docstring so that it will be one shorter sentence with or without further explanation in the docstring body.

**Comment by jackwilsdon** [comment]
PEP 8 has a [maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) of 79 characters.

The issue with rephrasing them is that some cannot easily be rephrased without losing some or all meaning.

**Comment by Nurdok** [comment]
You don't have to lose any meaning - you can elaborate as much as you want in the docstring body. You just need to rephrase the first sentence to be short and to the point. That's the whole idea of having a one-liner sentence at the beginning of the doctring, so it's totally intentional and won't be changed.

**Comment by bluetech** [comment]
I know this is closed, but in any case: I also think that the strict one-line rule is not optimal.

Sometimes, it is just not possible to fit a proper description sentence in the one line while still keeping reasonable line length, no matter how you rephrase it.  And with things like nested classes you already start 4 levels deep, which makes it harder.

Of course, you can just let the summary sentence go on to the right; but this is both ugly and hurts readability (it is easier to read prose when it is wrapped).

So for now I disable the relevant error codes, but then I lose the period-at-end-of-sentence warning which is what I wanted to enforce :)
