### ISSUE TITLE
New bugfix release

### ISSUE THREAD

**Issue by blueyed** [PyCQA/pydocstyle#194]
It would be nice to have a new release, since the bug where filenames are getting lowercased is very annoying (https://github.com/PyCQA/pydocstyle/pull/181).

From the milestones it looks like 1.1.0 is meant to get some more things in, so maybe 1.0.1 could be released with selected bug fixes only (in case master is not considered to be stable enough at the moment)?!

Thanks!

**Comment by Nurdok** [comment]
While trying to release a version, I encountered #196, so it'll take some more time until it is fixed. Sorry, I am working on it.

**Comment by Nurdok** [comment]
It took a LONG time, but I just published version 1.1.0.

https://github.com/PyCQA/pydocstyle/releases/tag/1.1.0
