### ISSUE TITLE
Errors should be printed to stdout

### ISSUE THREAD

**Issue by gvanrossum** [PyCQA/pydocstyle#201]
In #26 and #29 you changed errors to be printed to stderr. But actually for a linter that's quite inconvenient when you want to post-process the output. I checked flake8, pycodestyle, pyflakes and they all write their errors to stdout (and so does mypy).

Only errors that cause the program to exit immediately (e.g. command line syntax or can't open file) should go to stderr; the expected output (diagnostics about doc style) should go to stdout.

Please?

**Comment by sigmavirus24** [comment]
@gvanrossum as a way to side-step this, is it possible for you to use flake8-docstrings?

**Comment by gvanrossum** [comment]
Well, I side-stepped it using `2>&1`. :-)

And now that I've installed flake8-docstrings all my flake8 runs
automatically invoke it, which I don't appreciate. (I suppose there's a
config flag to disable it.) But it does write to stdout, and the errors are
parseable by Emacs command mode, so I'm still reasonably happy with it.

Still, I think as a matter of principle all linters should write to stdout,
not to stderr, since that is their principal output.

**Comment by Nurdok** [comment]
This seems reasonble, but as always, will take me some time to get to. Thanks for opening the issue.

**Comment by varunagrawal** [comment]
I got this once we touch Oct 1!

**Comment by lqaz** [comment]
@varunagrawal Reminder to merge.

**Comment by varunagrawal** [comment]
Pushed update to #210. Can someone review it please?

**Comment by Nurdok** [comment]
@varunagrawal I assure you I'll review it, but you'll have to be patient as is might take me a while.

**Comment by varunagrawal** [comment]
@Nurdok sounds good. :)
