### ISSUE TITLE
pydocstyle 1.1.0 isn't compatible with flake8

### ISSUE THREAD

**Issue by danieljacobs1** [PyCQA/pydocstyle#207]
We have started seeing errors in our flake8 output upon upgrading to the newest version of pydocstyle (1.1.0). We normally use pydocstyle through flake8. The errors were like the below:

`flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "D" due to module 'pydocstyle' has no attribute 'Error'.`

And indeed, when I run: `python -c "import pydocstyle; print(dir(pydocstyle))"`

I can see that there are many symbols not present in 1.1.0 that are present in 1.0.0:

```
$ python -c "import pydocstyle; print(dir(pydocstyle))" # pydocstyle version 1.1.0

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'check', 'checker', 'config', 'parser', 'utils', 'violations']

 $ python -c "import pydocstyle; print(dir(pydocstyle))" # pydocstyle version 1.0.0

['AllError', 'AttrDict', 'CheckConfiguration', 'Class', 'ConfigurationParser', 'D100', 'D101', 'D102', 'D103', 'D104', 'D105', 'D1xx', 'D200', 'D201', 'D202', 'D203', 'D204', 'D205', 'D206', 'D207', 'D208', 'D209', 'D210', 'D211', 'D2xx', 'D300', 'D301', 'D302', 'D3xx', 'D400', 'D401', 'D402', 'D403', 'D4xx', 'Decorator', 'Definition', 'Error', 'ErrorRegistry', 'Function', 'INVALID_OPTIONS_RETURN_CODE', 'IllegalConfiguration', 'Method', 'Module', 'NO_VIOLATIONS_RETURN_CODE', 'NestedClass', 'NestedFunction', 'PEP257Checker', 'Package', 'Parser', 'RawConfigParser', 'RunConfiguration', 'Set', 'StringIO', 'Token', 'TokenKind', 'TokenStream', 'VARIADIC_MAGIC_METHODS', 'VIOLATIONS_RETURN_CODE', 'Value', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'ast', 'chain', 'check', 'check_for', 'check_initialized', 'conventions', 'copy', 'defaultdict', 'dropwhile', 'humanize', 'is_ascii', 'is_blank', 'is_magic', 'itertools', 'leading_space', 'log', 'logging', 'main', 'main_pep257', 'namedtuple', 'os', 'parse', 're', 'run_pydocstyle', 'setup_stream_handlers', 'string', 'sys', 'takewhile', 'tk', 'tokenize_open', 'with_statement']
```
Clearly `flake8` is expecting `Error` (at the very least), which is the problem.

However, the `__all__` of `pydocstyle` only includes `check`, so it might not be appropriate for `flake8` to be accessing the other symbols.

**Comment by Nurdok** [comment]
It seems like `flake8-docstrings` is accessing the private `Error` class, which was moved (and was not considered an API change since it was private).

@sigmavirus24 or me could fix this in `flake8-docstrings`, but maybe I should also release a bugfix version of `pydocstyle` that preserves the previous `Error` import (by importing it in `__init__.py`)?

**Comment by sigmavirus24** [comment]
So we can yak-shave this, but there was no public API way back when. Further, when you return an object from your sole public API that object becomes a public API (`check` yields `Error`s). I don't have the time right now to fix this or create a release. I recommend folks pin to and older `pycodestyle`.

**Comment by sigmavirus24** [comment]
And further yet, I didn't catch this when reviewing the refactor so I blame myself entirely for this. I just have limited use of my hands right now (I've severely injured my arms) and so the amount of computer time I have is very very little

**Comment by Nurdok** [comment]
@sigmavirus24 I had no intention of assigning blame or anything of this sort!
The thing about `check` yielding `Error`s is a pretty convincing argument for me to add it to our public API. 

@danieljacobs1 at the moment, pinning `pydocstyle` to `1.0.0` should be a reasonable workaround for now. 

I'll try to get a bugfix version of `pydocstyle` out that adds `Error` to the API (and see if `flake8-docstrings` requires anything else as well).

**Comment by danieljacobs1** [comment]
Thanks guys.

**Comment by sigmavirus24** [comment]
@Nurdok I know you weren't trying to blame me. I just didn't want my comment to come across as blaming you either. :) That's why I clarified that I blamed myself for this.

**Comment by ssbarnea** [comment]
I would argue that this kind of bug is a good enough reason for removing a released package from PYPI server, at least until it is fixed.

**Comment by Nurdok** [comment]
I just release 1.1.1:
https://github.com/PyCQA/pydocstyle/releases/tag/1.1.1
https://pypi.python.org/pypi/pydocstyle/1.1.1

Please check if it solves your problem (running locally for me, I was able to run it via `flake8`).

**Comment by danieljacobs1** [comment]
We've tested 1.1.1 and it works fine with `flake8` for us too. Thanks @Nurdok.

**Comment by danieljacobs1** [comment]
Closing this issue as it's solved.
