### ISSUE TITLE
Add an api?

### ISSUE THREAD

**Issue by goanpeca** [PyCQA/pydocstyle#211]
I am working currently on a small library to unify all different available tools around python and I was wondering if there was a plan to have an api that would provide results as a dictionary, or at least add a `--json` flag to the command so it can be parsed easily. Using regex feels clunky

Something along the lines of

```python
from pydocstyle.api import check

results = check(...)

# Where results would store the info as
results = {
    'filepath1.py':
        {
        'problems:
            [{'line': '#', 'col': '#', 'code': '###', 'message': ''}, ...],
        'error': '',
    },
    'filepath2.py':
        {
        'problems:
            [{'line': '#', 'col': '#', 'code': '###', 'message': ''}, ...],
        'error': '',
    }
}

```

**Comment by Nurdok** [comment]
There is already an API - `from pydocstyle import check`. It returns an iterable of `Error` object, which you can use to construct that JSON output, or any other formatting you'd like.

**Comment by Nurdok** [comment]
Also, take a look at `flake8`: https://gitlab.com/pycqa/flake8

**Comment by goanpeca** [comment]
:+1:
