### ISSUE TITLE
Checks for docstring line lengths

### ISSUE THREAD

**Issue by brianv0** [PyCQA/pydocstyle#228]
PEP8 recommends doc strings actually be 72 characters or less, and it'd be nice to have a way to check for docstring length.

This may be a bit controversial as this project itself would violate the 72 character recommendation, but it does adhere to the 79 character recommendation. Meanwhile, PEP8 also mentions a relaxed 100 character line length:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

It may be tough to reconcile these, but I a check that verifies that all doc strings are less than 79 characters would be less controversial (as this project meets those standards) as well as a potential additional 72 character length check that could be added in the future.

**Comment by peterjc** [comment]
Please support the same ``--max-line-length=n`` command line API as ``pycodestyle`` if this is added.

**Comment by brianv0** [comment]
This issue was actually implemented in pycodestyle instead of pydocstyle

**Comment by peterjc** [comment]
Thanks @brianv0 - cross reference issue https://github.com/PyCQA/pycodestyle/issues/344 and pull request https://github.com/PyCQA/pycodestyle/pull/674

This added new command line option ``--max-doc-length=n`` and warning ``W505 doc line too long`` which is ignored by default.
