### ISSUE TITLE
1.2 Release?

### ISSUE THREAD

**Issue by jacebrowning** [PyCQA/pydocstyle#239]
There have been 88 commits since the 1.1.1 release on October 4, 2016 and the 1.2.0 milestone is 5 months overdue. Can we get a new release?

**Comment by Nurdok** [comment]
The next version is managed here:
https://github.com/PyCQA/pydocstyle/projects/1
It will be 2.0.0 since there were major changes. It will probably take a few more weeks, but I want to get a big refactoring I've been working on merged.

**Comment by peterjc** [comment]
And v2.0.0 out 👍  , so time to close this issue?

**Comment by Nurdok** [comment]
Yep!
