### ISSUE TITLE
How to fix error D213?

### ISSUE THREAD

**Issue by htiga** [PyCQA/pydocstyle#242]
I find that no matter how I write multi-line docstring, there is an error D213. Even the source code of pydocstyle itself below: [source code of pydocstyle that raises D213](https://github.com/PyCQA/pydocstyle/blob/286d9336f05d4a4fa9f0f0e7d2d42423467736e4/src/pydocstyle/checker.py#L263). Is this a bug or do I miss anything?

```python
def check_multi_line_summary_start(self, definition, docstring):
    """D21{2,3}: Multi-line docstring summary style check.

    A multi-line docstring summary should start either at the first,
    or separately at the second line of a docstring.

    """
    if docstring:
        start_triple = [
            '"""', "'''",
            'u"""', "u'''",
            'r"""', "r'''",
            'ur"""', "ur'''"
        ]

        lines = ast.literal_eval(docstring).split('\n')
        if len(lines) > 1:
            first = docstring.split("\n")[0].strip().lower()
            if first in start_triple:
                return violations.D212()
            else:
                return violations.D213()
```

**Comment by Nurdok** [comment]
D212 and D213 are mutually exclusive. You should enable one or none of them. By default, they are both disabled, but if you used the `ignore` flag, you need to also add them. Alternatively, you can use `add-ignore` instead. Seeing your command line and configuration file could help if you're still having problems.

**Comment by htiga** [comment]
Thanks for reply. Just as you say, I use the `ignore` flag with D101 but without D212 or D213. I add D213, problem solved.
```sh
pydocstyle --ignore=D101,D213
```
