### ISSUE TITLE
Config file options are not all valid

### ISSUE THREAD

**Issue by dayling** [PyCQA/pydocstyle#244]
I tried setting up a ".pydocstyle.ini" as my config file, however it wasn't detected on execute. I've worked around it be calling it ".pydocstyle". Either the documentation should be updated or the config file option allowed.

**Comment by Nurdok** [comment]
The `ini` extension is a new feature. You are probably reading the "latest" documentation which describe the development branch. You can see the "stable" version documentation here: http://www.pydocstyle.org/en/stable
