### ISSUE TITLE
Multi-line entries in configuration file

### ISSUE THREAD

**Issue by peterjc** [PyCQA/pydocstyle#250]
Related tool ``flake8`` explicitly supports multi-line configuration entries (which can be intermixed with comments) as described in http://flake8.pycqa.org/en/latest/user/configuration.html

e.g.

```
[flake8]
# it's not a bug that we aren't using all of hacking
ignore =
    # F812: list comprehension redefines ...
    F812,
    # H101: Use TODO(NAME)
    H101,
    # H202: assertRaises Exception too broad
    H202,
    # H233: Python 3.x incompatible use of print operator
    H233,
    # H301: one import per line
    H301,
    # H306: imports not in alphabetical order (time, os)
    H306,
    # H401: docstring should not start with a space
    H401,
    # H403: multi line docstrings should end on a new line
    H403,
    # H404: multi line docstring should start without a leading new line
    H404,
    # H405: multi line docstring summary not separated with an empty line
    H405,
    # H501: Do not use self.__dict__ for string formatting
    H501
```

I would like to be able to do the same in ``.pydocstyle`` for our ``ignore =`` list in order to comment why we ignore some entries, and facilitate merging edits to the file.

In my testing with pydocstyle v2.0.0 an example like this fails (it seems to use an empty ignore list).

**Comment by peterjc** [comment]
For anyone else with a similar use case, I decided to stop running ``pydocstyle`` directly, and instead use it via ``flake8`` with the ``flake8-docstring`` plugin. This means I can put the D### codes into a ``.flake8`` configuration file.

**Comment by FarmerSez** [comment]
Done in #281 🖖
