### ISSUE TITLE
--source is broken

### ISSUE THREAD

**Issue by brbsix** [PyCQA/pydocstyle#256]
The `--source` option is broken. Output looks like:

	src/pydocstyle/violations.py:87 in public method `__lt__`:
		    D105: Missing docstring in magic method

	876:     def __lt__(self, other):
		87:     def __lt__(self, other):
	886:         return (self.filename, self.line) < (other.filename, other.line)
		88:         return (self.filename, self.line) < (other.filename, other.line)

When it (presumably) should look like:

	src/pydocstyle/violations.py:87 in public method `__lt__`:
		    D105: Missing docstring in magic method

	87:     def __lt__(self, other):
	88:         return (self.filename, self.line) < (other.filename, other.line)

The issue originates in `Errors.lines`, found here: https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/violations.py#L49

It looks like some code may have been committed accidentally before it was complete.

**Comment by Nurdok** [comment]
Fixed by #260 .
