### ISSUE TITLE
D100 on import os

### ISSUE THREAD

**Issue by SitiSchu** [PyCQA/pydocstyle#266]
I get a `D100 Missing docstring in public module` for `import os`. Maybe add an option to ignore Built-in Modules ?

**Comment by Nurdok** [comment]
Hi @SitiSchu, I guess that `import os` is simply the first line of your undocumented module. The error refers to the file calling `import os`, not to the actual `os` module.

**Comment by SitiSchu** [comment]
Hello @Nurdok, yep adding a Docstring to the module fixed it. Thanks and sorry for bothering you :)
