### ISSUE TITLE
Class docstring does not need blank line before

### ISSUE THREAD

**Issue by benf-wspdigital** [PyCQA/pydocstyle#267]
The PEP 257 recommendation for a class docstring states, in part:

> Insert a blank line after all docstrings […] that document a class -- generally speaking, the class's methods are separated from each other by a single blank line, and the docstring needs to be offset from the first method by a blank line.

That is covered (correctly) by the D204 check.

There is no mention of blank line *before* the class docstring. The D203 check is incorrect to require a blank line.

Please remove the D203 check as it is not a PEP 257 recommendation.

**Comment by benf-wspdigital** [comment]
I would argue, further, that Pydocstyle should check that there is *no* blank line between the `class` statement and the class docstring.

**Comment by Nurdok** [comment]
Hi @benf-wspdigital,

Pydocstyle contains checks for more than just PEP 257. Regarding `D203` - PEP 257 used to recommend a blank line before a class docstring. It has been edited to remove this recommendation and therefore `D203` is *not* checked by default in pydocstyle. It still exists so projects with the old standard can still remain consistent. To support the new recommendation, `D211` was a added to make sure *no* blank lines exists before a class docstring and it *is* enabled by default.

**Comment by benf-wspdigital** [comment]
> PEP 257 […] has been edited to remove this recommendation and therefore D203 is not checked by default in pydocstyle.

Which version of Pydocstyle disabled `D203` by default?

**Comment by benf-wspdigital** [comment]
How can a user interrogate `pydocstyle` to know which checks are default, which are disabled?

**Comment by Nurdok** [comment]
Version 0.7.0, you can see the release notes here: http://www.pydocstyle.org/en/latest/release_notes.html#october-9th-2015

**Comment by benf-wspdigital** [comment]
> Version 0.7.0, you can see the release notes here […]

Thanks, I see the release notes there.

I was getting the `D203` check by default, with Pydocstyle version “1.1.1”. What could have caused that?

How can a user interrogate Pydocstyle directly, to know which checks are default, which are disabled?

**Comment by Nurdok** [comment]
@benf-wspdigital Unfortunately, there is currently no way to interrogate `pydocstyle` as to the defaults. In you case, have you use the `--ignore` flag for some other error code? If so, it would bring back `D203` if you haven't specifically ignored it. You can use the `--add-ignore` instead if that's the case.
