### ISSUE TITLE
Not working with files without `*.py` extension

### ISSUE THREAD

**Issue by luator** [PyCQA/pydocstyle#269]
I have some executable Python scripts that do not have a file name extension (i.e. `script` instead of `script.py`).
Now I noticed that I don't get any warning for these files when running `pydocstyle`. As soon as I add the `.py`, it is working.

Is this indented behaviour for some reason or is it a bug?

**Comment by Nurdok** [comment]
You can change this behavior with the `--match` flag:
```
--match=<pattern>     check only files that exactly match <pattern> regular
                      expression; default is --match='(?!test_).*\.py' which
                      matches files that don't start with 'test_' but end
                      with '.py'
```

See [usage documentation](http://www.pydocstyle.org/en/latest/usage.html).

**Comment by luator** [comment]
Ah, I briefly checked the documentation but somehow missed that. Thanks and sorry for the effort.

**Comment by Nurdok** [comment]
No problem.
