### ISSUE TITLE
improve experience when attempting install on python2.6

### ISSUE THREAD

**Issue by mr-c** [PyCQA/pydocstyle#271]
follow up to https://github.com/PyCQA/pydocstyle/issues/206

- [ ] add `python_requires='>=2.7` to `setup.py` https://stackoverflow.com/a/42792413/1585509
- [ ] try to fail early with nice message if installed with older pip/setuptools ?

**Comment by sigmavirus24** [comment]
The second option requires we do some hacky detection in `setup.py` which really won't go very far, honestly, especially if pip is new enough to prefer wheels.

**Comment by Nurdok** [comment]
This sounds okay, PRs welcome.

**Comment by aphedges** [comment]
The final Python 2.6 release was way back in 2013 (<https://peps.python.org/pep-0361/#release-schedule>), and `python_requires` has been properly set since eebb17b37401235a79836ca83b6135b76d457c77, so the changes requested here are no longer needed.
