### ISSUE TITLE
Allow __init__ to not have a docstring

### ISSUE THREAD

**Issue by mitar** [PyCQA/pydocstyle#273]
I prefer to have docstring for __init__ as part of the class docstring. Currently it seems there is no way to disable just the requirement for the __init__ docstring.

**Comment by sigmavirus24** [comment]
`__init__` should be considered a "magic" method and thus should be reported as D105. You can ignore D105 altogether to get rid of that.

**Comment by mitar** [comment]
Currently it is ignored [as a magic method](https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/parser.py#L208). But yes, as a workaround I patched `VARIADIC_MAGIC_METHODS` to not contain `__init__`.

But because it seems there are different ways people would like this, maybe for `__init__` there could be a configuration.

**Comment by Nurdok** [comment]
I think this is common enough to merit a dedicated `D1xx` error code.

**Comment by AndrewPashkin** [comment]
Numpy docstring guide specifically [says][1]:
>  The constructor (__init__) should also be documented here [in a class docstring]... 

[1]: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#id7

**Comment by Nurdok** [comment]
@AndrewPashkin This is already merged :)

**Comment by AndrewPashkin** [comment]
@Nurdok, the merge request just created a dedicated error code for that. But Numpy rules state that `__init__` SHOULD be documented in the class docstring and so it's not an error for `__init__` to not have a docstring.

**Comment by mitar** [comment]
Yes, so people who are using Numpy rules can configure pydocstyle to ignore that dedicated error. I think requiring D101 also requires one to document constructor in class docstring, no?

**Comment by AndrewPashkin** [comment]
But in Numpy rules it's not an error at all.

**Comment by Nurdok** [comment]
Seems to me that if this is the case, it's a simple matter of removing D107 from being on by default in the `numpy` convention.
