### ISSUE TITLE
Add Google docstring convention 

### ISSUE THREAD

**Issue by pmatos** [PyCQA/pydocstyle#275]
There are lots of projects out there using the google docstring convention. Given numpy has been recently added under #129, this is a request to add the google docstring convention.

Comparison between the two can be found [here](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#google-vs-numpy).

**Comment by FarmerSez** [comment]
@Nurdok , How about 'dem entry points? 😄

**Comment by anotherbugmaster** [comment]
Are there really much projects using Google style? I couldn't find even 5. It's poorly documented and doesn't have syntax for complex types such as List[Tuple(int, float)].

**Comment by anotherbugmaster** [comment]
What's bothers me more is that current style checker makes no distinction between Numpy and Google style docstrings.

**Comment by shacharoo** [comment]
@anotherbugmaster could you elaborate? 
As I see it, `pydocstyle` recognizes a set of errors. The so called "conventions" are only presets that define which are selected and which are ignored.
`Google` and `numpy` conventions are pretty much the same, it's not up to `pydocstyle` to recognize which is which.

**Comment by DanCardin** [comment]
Yea I was looking for google style also. It would be nice if it would enforce rules like google section rules ending in ":" (best i can get currently is disabling 406 and 407), and e.g. Args, Raises, and Returns section bodys being indented, and each line being formatted like
```
Args:
    param (optional type): description
```

**Comment by anotherbugmaster** [comment]
@shacharoo They look similar, but definitely not the same. Here's the main differences:
* [Quite comprehensive specification](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) for Numpy style; no specification at all for Google style (besides the couple of examples in the Google Python Style Guide)
* Correct Pycharm highlighting for Numpy style; Everything more complex than primitive types are incorrectly highlighted with Google Style
* Numpy style is more compact horizontally; Google Style is more compact vertically
* Numpy style has dashlines; Google Styles has tabs (which are subjectively more convenient)

So, if one wants a correct rendering of type annotations for Python 2, she should stick with Numpy Style. Otherwise, of course, it doesn't really matter.

In my case I really want to have those types and Google Style should be prohibited.

**Comment by anotherbugmaster** [comment]
Actually, look what I've found:

https://github.com/numpy/numpydoc

Numpy already has a tool that checks that docstings are in correct Numpy style. Would be nice if somebody implemented it in pydocstyle.

**Comment by shacharoo** [comment]
@anotherbugmaster yes, I know they are not the same convention 😄
You wrote: `"What's bothers me more is that current style checker makes no distinction between Numpy and Google style docstrings."`. What do you mean by that? `pep257` and `numpy` are the only conventions supported now. If you'll run `pydocstyle` on a file that has Google docstring conventions it will definitely return errors.

**Comment by anotherbugmaster** [comment]
Nope, at least in some cases it won't. I'll provide you with an example later.

**Comment by ermik** [comment]
Is there interest in adding Google's convention to pydocstyle? Getting it `well-documented` might be something I can help with.

**Comment by gunny-probably** [comment]
Is this a open source project? Might be down to put in some hours to support Google style.

**Comment by dickreuter** [comment]
Currently there is no error if the input arguments are not listed at all in the docstring or if the format is different.

**Comment by demus** [comment]
Checking in to see if anyone is working on this?

**Comment by Nurdok** [comment]
@demus not that I'm aware.

**Comment by demus** [comment]
Started working on it here: https://github.com/demus/pydocstyle/tree/google-style-docstrings

**Comment by ermik** [comment]
Jumping back in after a long time in a lot of projects. @demus I'd be glad to take part somehow.

**Comment by eterna2** [comment]
@demus any progress so far? Would be nice to have google style docstring supported.

**Comment by dickreuter** [comment]
Especially if it would enforce that all parameters of a function are mentioned in the docstring. That’s probably the most required feature.

**Comment by samj1912** [comment]
If no one else is working on this actively, I would like to take this up.

**Comment by samj1912** [comment]
Since the actual convention is pretty loosely defined, I started a PR draft here - 
https://github.com/PyCQA/pydocstyle/pull/357
based on my observations from the sources I have provided.

**Comment by demus** [comment]
My bad, I haven't made progress on this. Got distracted with other things, sorry!

**Comment by samj1912** [comment]
I am done with a basic implementation in https://github.com/PyCQA/pydocstyle/pull/357

Will continue to add features over time.

**Comment by dickreuter** [comment]
Is it possible to assert that all function parameters are mentioned in the docstring?

**Comment by samj1912** [comment]
@dickreuter that is on my TODO list, but the current PR is getting big and I don't want to add more features to it.

I will create those PRs once the current one is reviewed.

**Comment by samj1912** [comment]
@dickreuter I was able to squeeze in the function arg check with surprisingly less amount of code.
So I added support for it (D417) See https://github.com/PyCQA/pydocstyle/pull/357/commits/c02884919e3f3708a1343443b52cb9b69434663c

**Comment by samj1912** [comment]
@Nurdok I guess this can now be closed?
