### ISSUE TITLE
Test wheel dists installation in CI

### ISSUE THREAD

**Issue by FarmerSez** [PyCQA/pydocstyle#290]
Opened due to #289.
I think this should be checked for the latest in every (supported) major python version (i.e. 2.7 and 3.6), not for the entire build matrix. @Nurdok?

**Comment by Nurdok** [comment]
I think that given our current Travis configuration it will actually be easier to just test on all Python version, so I don't see a reason to limit this. Overall, this is a great idea.

**Comment by FarmerSez** [comment]
Done in #292 .
