### ISSUE TITLE
Incoherent code line raising ParseError

### ISSUE THREAD

**Issue by rubenseam** [PyCQA/pydocstyle#293]
I'm trying to develop a plugin to Flake8, for pĺain syntax checking. I've installed the library, and installed pydocstyle as well, which is a dependency. However, depending on the file I use as input to 'pydocstyle', it gives me the error:

```
$ pydocstyle
WARNING: Error in file ./setup.py: Cannot parse file.      
WARNING: Error in file ./smarttcheck.py: Cannot parse file.
```

Wandering through the code, I've eventually found the error was coming from line:
https://github.com/PyCQA/pydocstyle/blob/df872e43915bcb6d94a334fff9c879574f78abc4/src/pydocstyle/parser.py#L292

In the same parser.py source file, at line 8, you guys do the following import:
https://github.com/PyCQA/pydocstyle/blob/df872e43915bcb6d94a334fff9c879574f78abc4/src/pydocstyle/parser.py#L8
Which, I believe, invalidates the use of `compile` at line 292.

My "issue/question" is: is that line intentional, or was it a typo? When I comment it out, the files are checked properly by pydocstyle. Sorry for duplicates, or for a potentially non-sensical issue submission.
For some reason I fail to see, some files pass through this check without raising the error.

**Comment by Nurdok** [comment]
The use of `compile` in the first line you mentioned is the built-in `compile`, which makes sure the file has a legal Python syntax (in the same Python version). Are you sure that `setup.py` (for example) are correct Python files?

**Comment by rubenseam** [comment]
Thanks for the reply! The contents of files were, for file 'setup.py':
```
# -*- coding: utf-8 -*-
import setuptools
from __future__ import with_statement


requires = [
    "flake8 > 3.0.0",
]

flake8_entry_point = "flake.formatting"

setuptools.setup(
    name="smarttcheck",
    license="SMARTTBOT",
    version="1.0.0",
    description="SmarttCheck defines coding standards for SmarttBot sources.",
    author="SMARTTBOT",
    author_email="dev@smarttbot.com",
    url="https://smarttbot.com/sthsth",
    packages=[
        "smarttcheck",
    ],
    install_requires=requires,
    entry_points={
        flake8_entry_point: [
            'X = smarttcheck:SmarttCheck',
        ],
    },
    classifiers=[
        "Framework :: Flake8",
        "Environment :: Console/Atom",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: SMARTTBOT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Quality Assurance",
    ]
)

and 'smarttcheck.py':
```
# -*- coding: utf-8 -*-


from sys import stderr
from flake8.formatting import base


class SmarttCheck(base.BaseFormatter):
"""
    Flake8's example formatter.
"""
    def format(self, error):
        print(error)
        print("HELLO, BAE!", file=stderr)
        return 'Example formatter: {0!r}'.format(error)
```

**Comment by Nurdok** [comment]
You indeed have a syntax error in `setup.py`: `from __future__` import MUST be the first line of the file that is not empty or a comment. So switch the two `import` statements and you'll be good to go.

**Comment by Nurdok** [comment]
In the second file you also have a syntax error where the docstring is too dedented. 
It should be:

```.py
 # -*- coding: utf-8 -*-

from sys import stderr
from flake8.formatting import base

class SmarttCheck(base.BaseFormatter):
    """
    Flake8's example formatter.
    """
    def format(self, error):
        print(error)
        print("HELLO, BAE!", file=stderr)
        return 'Example formatter: {0!r}'.format(error)


```

**Comment by rubenseam** [comment]
Ah, I see. I thought those errors would come out as a set of reported errors, instead of a "Parse error".
All is well now! Thank you very much for the promptness in addressing my issue.

Kind regards!

**Comment by rubenseam** [comment]
Ah, I see. I thought those errors would come out as a set of reported errors, instead of a "Parse error".
All is well now! Thank you very much for the promptness in addressing my issue.

Kind regards!
