### ISSUE TITLE
pydocstyle.org blocked as harmful

### ISSUE THREAD

**Issue by jfishe** [PyCQA/pydocstyle#294]
Charter Spectrum blocked the website as harmful.  Any idea what's going on?
Harmful web site blocked
http://pydocstyle.org
This web site has been reported as harmful. 
We recommend that you do not visit this web site.

 https://transparencyreport.google.com/safe-browsing/search?url=pydocstyle.org doesn't report any issues.

**Comment by shacharoo** [comment]
I tried talking to one of their representatives online and they have no clue why it's blocked. I was referred to a Tier 3 support team, but the international call rates suck 😃
They also said that it might not be a global problem, rather a problem with the specific account that is trying to access the site. 
@jfishe , Would you mind checking that with them? The number is 1-800-222-5355. 
Thanks.

**Comment by shacharoo** [comment]
It seems like MS Sonar has some things to say about this:
https://sonarwhal.com/scanner/5b616262-ccf7-48a1-968c-fe960ed3d736

Perhaps one of them is the reason for the filter in Spectrum.

**Comment by jayvdb** [comment]
"pytdocstyle.org" in issue title should be changes to "pydocstyle.org" ;-)

**Comment by samj1912** [comment]
Closing this as it has been inactive for a while. Please feel free to re-open if this is still relevant.
