### ISSUE TITLE
Documentation Example for Config errors

### ISSUE THREAD

**Issue by erichiller** [PyCQA/pydocstyle#296]
The [config example](http://www.pydocstyle.org/en/2.1.1/usage.html#example) has 

`match = *.py
`
This is invalid and throws an error when used as a config file option.

**Comment by Nurdok** [comment]
Thanks for reporting this @erichiller!

I started working at Google recently and I am in the process of getting an exemption for pydocstyle regarding intellectual property. This means that for now I am unable to make new code contributions, but I can still participate in issue, approve PRs and so on. So, it might take me a while to get to fixing this myself - PRs are welcome :)
