### ISSUE TITLE
D401 should be avoided for property

### ISSUE THREAD

**Issue by ederag** [PyCQA/pydocstyle#301]
`pydocstyle` yields 

> D401 First line should be in imperative mood

for properties docstrings such as
```
    @property
    def config(self):
        """Configuration dictionary."""
        return {'x': self.x, 'y': self.y}
```
Of course the docstring could be changed to 
`Return the configuration dictionary.`, or `Get the configuration dictionary.`,
but this imperative mood seems less natural, 
because properties are used as attributes, not functions.

This was already mentioned in	https://github.com/PyCQA/pydocstyle/issues/68#issuecomment-51980479, but lost below other considerations.

Some ignore D401 altogether because of this issue: https://github.com/flycheck/flycheck/commit/79e5cd45e69cfed89048a47e0a922e0ef781a611

**Comment by kblicharski** [comment]
The only current workaround for this is passing `--ignore-decorators=property` or adding `ignore-decorators=property` to your .pycodestyle file. I believe this excludes all checks from properties, not just D401, so it's suboptimal.

**Comment by ederag** [comment]
@kblicharski If it excludes all checks for properties, I will not use that workaround.
But thanks, that was interesting.

**Comment by Nurdok** [comment]
Coming back to this as #444 was opened - I'm not sure this is a good idea. Usually when a class exposes a property, it's because it requires some computation to produce (otherwise it could have exposed a public attribute). The docstring can be used to describe how this attribute is computed, e.g. "Fetch X from database" or "Compute X", etc.

I'm not sure that adding changing "X" to "Get X" is so cumbersome that it justifies the cases where a strong verb can really help understand what's going on.

To the point that a property is used as an attribute - well, that's not really true. If you have both a getter and a setter property method, do you document them both the same? I would say no, you document each with what it does - one gets and one sets.

**Comment by ederag** [comment]
> To the point that a property is used as an attribute - well, that's not really true. If you have both a getter and a setter property method, do you document them both the same? I would say no, you document each with what it does - one gets and one sets.

That makes sense.

But there is another point of view, where *verb indicates a method*.
On the contrary, property is used without parentheses (no call).
Here is an example:
https://github.com/ederag/geoptics/blob/f1ae7186049cd40bfc6523a40f6cecd379ecf2d5/geoptics/elements/scene.py#L128-L139
and the corresponding documentation:
![image](https://user-images.githubusercontent.com/10962809/72184607-17580200-33f1-11ea-9f11-c5f6448d2c4d.png)
That's it, setter is not documented at all.

Either the get/set time is negligible, 
or a note is given in the property docstring itself.

**Comment by robertschweizer** [comment]
> Coming back to this as #444 was opened - I'm not sure this is a good idea. Usually when a class exposes a property, it's because it requires some computation to produce (otherwise it could have exposed a public attribute). The docstring can be used to describe how this attribute is computed, e.g. "Fetch X from database" or "Compute X", etc.

True, a property often does some computation. But that's usually very simple. For example, `pathlib.Path.name` evaluates one if-condition: https://github.com/python/cpython/blob/3.8/Lib/pathlib.py#L797-L803 (BTW, here the stdlib isn't using imperative mood for a property docstring).
Other properties simply return a private attribute. 

To me, the point of a property is to look like an attribute to the user. For something expensive, I'd always expose a method. If an property can be used like an attribute, I don't see why we shouldn't document them the same. For expensive things, expose a method and use imperative mood in its docstring.

> I'm not sure that adding changing "X" to "Get X" is so cumbersome that it justifies the cases where a strong verb can really help understand what's going on.

It's never hard to change a docstring. The question is if we should really ask people to change it. Does every read-only attribute implemented as a property have to use imperative mood in its docstring? 

Being too strict here will make people disable D401, and lose its value for normal methods. As we've seen happening above.

**Comment by samj1912** [comment]
A possible alternative to this could be, that rather than adding a blanket wide check to disable all codes for decorators/disabling D401 for property methods, we could add a way to disable some checks for decorated methods.

**Comment by e-gebes** [comment]
This is a duplicate of https://github.com/PyCQA/pydocstyle/issues/531 which is already implemented.

**Comment by ederag** [comment]
*Technically #531 is the duplicate, not the reverse (this issue is older).*
Thanks for the fix ! Closing.
