### ISSUE TITLE
Upload tests to PyPI

### ISSUE THREAD

**Issue by dotlambda** [PyCQA/pydocstyle#302]
Please upload the files in `src/tests` to PyPI.

**Comment by sigmavirus24** [comment]
As what package? They don't belong in the `.tar.gz` as that's meant to be installed by `pip`. Should they be uploaded as a separate package? Each release is tagged which means there's a full source checkout tagged and tarballed by GitHub. That includes tests.

**Comment by dotlambda** [comment]
Why do they not belong in the tarball? They definitely don't harm.
Having the tests is useful for integration tests, e.g. for package managers.
I'll use the GitHub tarball for now.

**Comment by sigmavirus24** [comment]
> Why do they not belong in the tarball? They definitely don't harm.

They do some harm. The tarballs are cached locally which means the larger the tarball the more of the user's disk we're taking up. The tarballs are also served via PyPI which is donated infrastructure, not just the server hosting the files but also the CDN that serves them most of the time. The more stress we put on the good will of the corporations donating this valuable infrastructure to us, the more precarious the community's service is.
