### ISSUE TITLE
Crash on invalid syntax without detail

### ISSUE THREAD

**Issue by fclaerho** [PyCQA/pydocstyle#303]
```bash
$ pydocstyle --version
2.1.1
```

### ISSUE

Currently pydocstyle crashes (with a stack trace, and no detail about the problem) on any syntax error.
As much as pydocstyle is not meant to validate a python source file (this is defer to e.g. pylint), this is still disturbing to have it crash without information when the user passes directories to scan.

I would suggest to at least exit gracefully with a message specifying which file was scanned and that the file is invalid.

### REPRODUCTION

Source file, anything invalid will do:
```python
# some_dir/foo.py
msg =
```

Expected output:
```bash
$ pydocstyle some_dir/ another_dir/ yet_another_dir/
fatal: some_dir/foo.py: invalid file
$ echo $?
1
```

Actual output:
```bash
Traceback (most recent call last):
  File "/Users/$user/Library/Python/2.7/bin/pydocstyle", line 11, in <module>
    sys.exit(main())
[…]
    module = parse(StringIO(source), filename)
  File "/Users/$user/Library/Python/2.7/lib/python/site-packages/pydocstyle/parser.py", line 305, in __call__
    return self.parse(*args, **kwargs)
  File "/Users/$user/Library/Python/2.7/lib/python/site-packages/pydocstyle/parser.py", line 294, in parse
    six.raise_from(ParseError(), error)
AttributeError: 'module' object has no attribute 'raise_from'
```

**Comment by sigmavirus24** [comment]
Can you share what you have installed? It looks like pydocstyle is trying to use `six.raise_from` which does exist in the six library but for some reason isn't available on your installation. Also, is it possible that you have a `six.py` in your current working directory that could be interfering here?

**Comment by Nurdok** [comment]
@sigmavirus24 is correct, it looks like the `six` import on your system works, but loads the wrong module. How did you install `pydocstyle`?

**Comment by fclaerho** [comment]
Ha, I see, pydocstyle requires six-1.11.0 but I'm on macOS 10.11 on which six is already pre-installed at version 1.4.1 system-wide and takes precedence.
