### ISSUE TITLE
Allow user to specify a particular file to run on

### ISSUE THREAD

**Issue by annawoodard** [PyCQA/pydocstyle#304]
Thanks to all the contributors for this great software!

I want to plug this into Vim, but I'm finding it not very straightforward to indicate a specific file I want to run on. The `match-dirs` option is great for selecting particular groups of matches, but because of the walk that happens [here](https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/config.py#L154) I'm finding it difficult to match a specific file which may be several layers deep with any combination of `match-dirs` and `match`. Am I missing something obvious here? Are there objections to just implementing a `--file` option which would take the filepath to be checked? If not, I can implement it.

**Comment by Nurdok** [comment]
Hi @annawoodard, thanks so much!
