### ISSUE TITLE
Please give us feedback about AST change in Python 3.7 

### ISSUE THREAD

**Issue by methane** [PyCQA/pydocstyle#305]
In Python 3.6, docstring was expression in AST.

    FunctionDef(name='foo', ..., body=[Expr(value=Str(s='docstring'))], ...)

Since docstring is special and it's unclear that expression is docstring or not, we changed AST in 3.7a1.
docstring is moved from body to field. ([bpo-29463](https://bugs.python.org/issue29463))

    FunctionDef(name='foo', ..., body=[], ..., docstring='docstring')

But it removed syntactic information about docstring (e.g. lineno).  We are considering changing it again.  Docstring is moved back to body, but it is special statement named `DocString(s)`. `Expr(value=Str(s))` is not docstring. ([bpo-32911](https://bugs.python.org/issue32911))

    FunctionDef(name='foo', ..., body=[DocString(s='docstring')], ...)

It means tools broken by 3.7a1 will be broken again.  But 3.7b3 will be the last chance to change AST.

How do you think about it?  Please give comment / vote on [the issue tracker](https://bugs.python.org/issue32911).

**Comment by Nurdok** [comment]
@methane we actually don't use the AST in pydocstyle, we use tokenize directly since we need the concrete tree, with formatting and such. So I'm not sure if my opinion is relevant to this discussion.

**Comment by lordmauve** [comment]
I believe the upstream proposal is dead. This issue can be closed.
