### ISSUE TITLE
D100 and unicode_literals

### ISSUE THREAD

**Issue by omercnet** [PyCQA/pydocstyle#306]
I couldn't find a good reference, sorry if I missed it - but should `from __future__ import unicode_literals` come before the module's docstring?

maybe it's a question for https://github.com/python/cpython but `__doc__` isn't populated unless the docstring is the first line, shouldn't the import come first otherwise the docstring should have a `u` prefix ?

**Comment by Nurdok** [comment]
The docstring must be the first thing in the module (other than blank lines or comments IIRC). The `__future__` import isn't like a regular import - it's syntactically different and must be the first thing in the module _excluding_ the docstring.

**Comment by omercnet** [comment]
thanks for the clarification
