### ISSUE TITLE
Incorrect D405 on lowercase "attributes" used in docstring.

### ISSUE THREAD

**Issue by TimZaman** [PyCQA/pydocstyle#311]
```py
    def clip(self, attributes_per_polyline):  # noqa: D405 (pydocstring bug)
        """
        Some stuff here.

        Args:
            attributes_per_polyline (tensor): attributes for each polyline.

        Returns:
            stuff
        """
```

Throws: 
`D405`
```
stuff.py:1337 in public method `clip`:
        D405: Section name should be properly capitalized ('Attributes', not 'attributes')
```
I think 'attributes' is seen as some kind of special keyword here by pydocstyle, which it isn't/doesn't have to be.

**Comment by shacharoo** [comment]
'Attributes' is a section name in the numpy docstring conventions. Although this is a bug (we recognize the prefix "attributes" of "attributes_per_polyline"), you should make sure you're using the right conventions for your project.

**Comment by TimZaman** [comment]
Our convention is Args.
