### ISSUE TITLE
FutureWarning: Possible nested set at position 1

### ISSUE THREAD

**Issue by vigo** [PyCQA/pydocstyle#345]
I have this warning:

    ...../python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
    EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')

- Python 3.7.0
- flake8 version 3.6.0 (flake8-blind-except: 0.1.1, flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, flake8_builtins: 1.4.1, flake8_commas: 2.0.0, flake8_quotes: 1.0.0, import-order: 0.18, mccabe: 0.6.1, naming: 0.7.0, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.0 on Darwin

**Comment by Nurdok** [comment]
Is there more context to this error? It looks like the error is in `pep8.py`, but since you have `pycodestyle` installed I'm not sure why you have this file. Can you reproduce this in a clean virtualenv? 

In any case I suspect this is a problem with py**code**style, not py**doc**style

**Comment by vigo** [comment]
yeah, thanks for the heads up!

**Comment by DylanYoung** [comment]
FYI: https://github.com/PyCQA/pycodestyle/issues/728
