### ISSUE TITLE
Include tests in source tarball

### ISSUE THREAD

**Issue by jayvdb** [PyCQA/pydocstyle#351]
The source tarballs should include the tests, so that packaging systems can use the pypi release tarballs to run the tests to validate the package in the built environment.

Also note that README.rst uses dos EOL.

c.f. https://build.opensuse.org/request/show/673404

**Comment by Nurdok** [comment]
There's already a PR for this with some discussion on whether this should be the case at all, you can contribute to the discussion in #252.

**Comment by sigmavirus24** [comment]
Closing to focus discussion on #252
