### ISSUE TITLE
__all__ is parsed incorrectly

### ISSUE THREAD

**Issue by webknjaz** [PyCQA/pydocstyle#352]
Causes warning:
```python
__all__ = 'exportable1', 'exportable2'
```

Works well:
```python
__all__ = ('exportable1', 'exportable2')
```

But both use valid tuple syntax so in the first case, `pydocstyle` is not supposed to yell at user.

**Comment by Nurdok** [comment]
Hi @webknjaz, thanks for reporting on this (and sorry for the delay in response)!
I'll try to get to this soon, but realisticly it'll take some time, so if you or someone else are interested in submitting a PR, that would be great.
