### ISSUE TITLE
NameError: name 'sesssion_token' is not defined

### ISSUE THREAD

**Issue by latalavera** [PyCQA/pydocstyle#371]
Hola buenas, soy nuevo en el mundo de la programacion, y practicando con las sesiones en flask, me da este error y no entiendo porque me dice que no esta definido cuando lo defino justo antes:

```
[@app.route('/', methods=["GET", "POST"])
def index():
    if request.method == "GET":
        data = {}
        session_token = request.cookies.get("session_token")                        #guardamos el valor de la cookie session token en la variable session_token

        if sesssion_token:
            user = db.query(User).filter_by(session_token=session_token).first()  #si tenemos una session token, miramos y comparamos en la base de datos
        else:                                                                       #si no creamos una instancia user vacia
            user = None

        data.update({'user': user})
        return render_template("index.html", data=data)](url)
```

**Comment by sigmavirus24** [comment]
Per [Google Translate](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=Hola%20buenas%2C%20soy%20nuevo%20en%20el%20mundo%20de%20la%20programacion%2C%20y%20practicando%20con%20las%20sesiones%20en%20flask%2C%20me%20da%20este%20error%20y%20no%20entiendo%20porque%20me%20dice%20que%20no%20esta%20definido%20cuando%20lo%20defino%20justo%20antes%3A)

> Hi, I'm new in the world of programming, and practicing with sessions in flask, I get this error and I do not understand why it says it is not defined when I define it just before:

----

@latalavera Hola, parece que abrió este informe contra el proyecto equivocado. No trabajamos en "Flask" y este proyecto no existe para ayudar a responder preguntas. Por favor intente usar https://stackoverflow.com

Hi there, it seems that you opened this report against the wrong project. We do not work on "Flask" and this project does not exist to help answer questions. Please try using https://stackoverflow.com
