### ISSUE TITLE
New PyPI Release, Publish

### ISSUE THREAD

**Issue by ljades** [PyCQA/pydocstyle#372]
A lot of the updates that have been made to pydocstyle on this repo since the 3.0.0 release have been extremely valuable. Are there any plans for a new release on PyPI anytime soon with these features?

If need be my team can do a pip install by the git hash but we'd rather do it if possible by PyPI release.

**Comment by Nurdok** [comment]
Seems reasonable to do this, sure :)
I'll try to get to release the new version this weekend (I hope).

**Comment by Nurdok** [comment]
4.0.0 is released, closing this issue.
