### ISSUE TITLE
Issue on pydocstyle version 4.0.0

### ISSUE THREAD

**Issue by kkkothari** [PyCQA/pydocstyle#375]
"flake8-docstrings" failed during execution due to "module 'pydocstyle' has no attribute 'tokenize_open'"

**Comment by ssoto** [comment]
Also affected here with incomprehensible message. We are using tox without `pydocstyle` version pinged.

As workaround, we pinged `pydocstyle` on tox.ini file to `pydcosteyle<4.0.0`

Regards!

**Comment by kevin-j-morse** [comment]
Looks like the flake8-docstrings people are going to deal with this from their end

https://gitlab.com/pycqa/flake8-docstrings/issues/36

**Comment by Gubarev** [comment]
> As workaround, we pinged `pydocstyle` on tox.ini file to `pydcosteyle<4.0.0`

For those, who use copy-paste to solve issues. Correct version restriction string:
`pydocstyle<4.0.0`

**Comment by zzzeek** [comment]
is it safe to come out yet? I feel kind of badly that pydocstyle is up to version 5.0.1 on pypi now but most of the world has probably pinned to <4.0.0.   Per https://gitlab.com/pycqa/flake8-docstrings/-/issues/36#note_199635329 it should be safe to set flake8-docstrings minimum to 1.3.1 and unpin pydocstyle.

**Comment by jnns** [comment]
We have yet to experience the aforementioned issue since unpinning and moving to: 

```
flake8-docstrings==1.5.0
pydocstyle==5.0.2
```

:+1:
