### ISSUE TITLE
Initiate imperative mood

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pydocstyle#377]
I'm getting a D401 should be imperative for:
`Initiate an a/b test.`

Unless I'm confusing my grammar, that is already in the imperative mood. 'Initiates' would be incorrect.

**Comment by sigmavirus24** [comment]
What happens if you remove the `/`

**Comment by Dreamsorcerer** [comment]
Nothing, error still happens with this docstring:
`"""Initiate test."""`

**Comment by Dreamsorcerer** [comment]
The exact output is:
`web/utils/ab_test.py:55:1: D401 First line should be in imperative mood`

**Comment by sigmavirus24** [comment]
Just making sure. I remember a `/` causing other problems in the past and wanted to verify that it hadn't cropped back up.

**Comment by Nurdok** [comment]
[I've added "initiate" to the imperative word whitelist](https://github.com/PyCQA/pydocstyle/commit/cc5a96b356e2f10e8c95f1ca719efa3380237671). Should work fine now.
Thanks for reporting this!

**Comment by lordmauve** [comment]
This is causing an issue (and failing tests) with:

```
D401: First line should be in imperative mood ('Initiate', not 'Initialize')
```

I looked into this and it's because the stemmer stems them both to `initi`.

The stemmer actually succeeds in stemming the British English `initialise`:

```python
>>> snowballstemmer.stemmer('english').stemWord('initialise')
'initialis'
```

So it looks like the stemmer is unaware of Americanisms. I am surprised. Perhaps we can teach it '-ize' endings?

**Comment by lordmauve** [comment]
Ah, you have [a feature branch for fixing this](https://github.com/PyCQA/pydocstyle/tree/feature/initiate).
