### ISSUE TITLE
ImportError: No module named 'typing'

### ISSUE THREAD

**Issue by myint** [PyCQA/pydocstyle#378]
Looks like #342 broke support for Python 3.4:

https://travis-ci.org/myint/autoflake/jobs/557940762#L626-L640

```
$ pydocstyle autoflake.py setup.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/bin/pydocstyle", line 7, in <module>
    from pydocstyle.cli import main
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pydocstyle/__init__.py", line 1, in <module>
    from .checker import check
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pydocstyle/checker.py", line 11, in <module>
    from . import violations
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pydocstyle/violations.py", line 6, in <module>
    from typing import Iterable, Optional, List, Callable, Any
ImportError: No module named 'typing'
The command "pydocstyle autoflake.py setup.py" exited with 1.
```

On Python 3.4, `typing` should be added to:

https://github.com/PyCQA/pydocstyle/blob/cc5a96b356e2f10e8c95f1ca719efa3380237671/setup.py#L9-L11

Note that #344 added this `typing` dependency under `requirements/tests.txt`, but that won't get invoked by normal users that install `pydocstyle` via `pip`.

**Comment by mrshannon** [comment]
While pydocstyle states that it currently supports Python 3.4, that version of Python went end-of-life 4 months ago (https://devguide.python.org/devcycle/#end-of-life-branches).

A decision should be made as to whether to continue to support Python 3.4 after end-of-life or not.  If the decision is to not support it this bug can be closed as it only effects Python 3.4.

**Comment by samj1912** [comment]
This should be closed now with https://github.com/PyCQA/pydocstyle/commit/c20721b8978812a81b49fc602538ee28577c5b76

**Comment by flutterq** [comment]
[[Solved] Pip command line “ImportError: No Module Named Typing”
](https://exerror.com/solved-pip-command-line-importerror-no-module-named-typing/)
