### ISSUE TITLE
Error codes missing from ReadTheDocs as of 4.0.0

### ISSUE THREAD

**Issue by lordmauve** [PyCQA/pydocstyle#380]
On ReadTheDocs, [the current error codes page](http://www.pydocstyle.org/en/4.0.0/error_codes.html) has a blank **Grouping** heading.

For the [3.0.0 release docs](http://www.pydocstyle.org/en/3.0.0/error_codes.html), this is where the table of error codes would be printed.

**Comment by peterjc** [comment]
I found this issue while trying to find documentation on new code ``D417: Missing arguments in the function docstring``, added in 6de6d938377e2db3bfe6f706fa2e3b90c412db76 as part of #357 (initial GoogleDoc convention).

I note that http://www.pydocstyle.org/en/4.0.0/error_codes.html#default-conventions is also missing documentation of the new ``google`` convention.

**Comment by peterjc** [comment]
There must have been a problem with the included file ``docs/snippets/error_code_table.rst`` (which is not under version control), it is meant to have been generated via ``docs/conf.py``

**Comment by lordmauve** [comment]
Ew, that sounds like a hack. Importing conf.py isn't supposed to have side-effects. Maybe ReadTheDocs is now caching the contents of `conf.py`?

**Comment by peterjc** [comment]
Importing ``conf.py`` is the accepted way to run ``sphinx-apidoc`` on RTD, and probably the only way to have any dynamic content on RTD - so I can see why that would be done.

Looking at the RTD build logs might be instructive...

**Comment by lordmauve** [comment]
I checked [the log of a recent build](https://readthedocs.org/projects/pydocstyle/builds/9463748/) and it doesn't look like they use caching - indeed they append extra build config to each `conf.py`.

**Comment by lordmauve** [comment]
Oh, here's the issue:

```
WARNING: snippets/error_code_table.rst:1: (ERROR/3) Malformed table.
```

**Comment by peterjc** [comment]
Looks like D415 broke the table - if so there are less fragile RST table layouts without the vertical bars which would work better here.

**Comment by peterjc** [comment]
Self-contained snippet for testing:

```
$ python -c "from pydocstyle.violations import ErrorRegistry; print(ErrorRegistry.to_rst())" > error_code_table.rst
```

```
$ pip install restructuredtext-lint
$ restructuredtext-lint error_code_table.rst
ERROR error_code_table.rst:1 Malformed table.
```

**Comment by lordmauve** [comment]
@Nurdok Could you tag a `4.0.0.post1` release in master? Simply tagging will update ReadTheDocs `stable` (but no need to upload a new package to PyPI).
