### ISSUE TITLE
No release on PyPI for 4.0

### ISSUE THREAD

**Issue by dopplershift** [PyCQA/pydocstyle#385]
There's no source release on PyPI for the 4.0 release:
![image](https://user-images.githubusercontent.com/221526/61657228-b4768100-ac7f-11e9-84cd-60de9e7ef801.png)
https://pypi.org/project/pydocstyle/#files

Was this intentional? Previous releases included it, so I wanted to confirm.

**Comment by AMDmi3** [comment]
`4.0.1` does have a proper source release, so this can probably be closed.
