### ISSUE TITLE
Author name(s) should be ignored

### ISSUE THREAD

**Issue by cassandriel** [PyCQA/pydocstyle#387]
Hi, I've recently started using pydocstyle on all of my code and generally run into a single problem. I put my name on top of all of my code. It tells me that I should end my line with a period, not the last letter of my last name. 

I tried looking for a solution using the terms "pydocstyle author name" but couldn't find anything. Other than telling pydocstyle to ignore that line, is there anything else I can do?

**Comment by cassandriel** [comment]
A somewhat strange behavior I discovered is this. This is not okay:
"""
Sifer Aseph

Test line
"""

But this is okay:
"""
Sifer Aseph.

Test line
"""

Not quite sure the rationale behind this but would appreciate any explanation. I tried looking up the doc but did not see anything.

**Comment by sigmavirus24** [comment]
Is this the module level docstring? If so, your name isn't the thing that describes the module.

More conventionally this is done:

```
# Copyright 2019 (c) Author
# License Text
"""Document the module being written.

This provides documentation to be displayed when using help() and other tools like Sphinx-doc.
"""

# code
```

I personally don't feel this is a bug nor that we can discern the difference between an human name and an invalid first line of the docstring.

**Comment by cassandriel** [comment]
Thank you, I'll work with that.
