### ISSUE TITLE
D417 for missing arguments is google only

### ISSUE THREAD

**Issue by peterjc** [PyCQA/pydocstyle#394]
In principle D417 (new in v4.0.0 c02884919e3f3708a1343443b52cb9b69434663c by @samj1912 as part of support for the Google coding style #275, further enhancement in #384 ) could be performed under the ``numpy`` convention, which has a well defined parameters section.

In fact, it could be applied to the default ``pep257`` convention with a simple substring check - are all the function arguments present anywhere in the docstring? This wouldn't catch everything but would be better than nothing?

**Comment by samj1912** [comment]
I added support for numpy style docs for now

**Comment by peterjc** [comment]
Ah, pull request #407 - looks good :)

**Comment by rademacher-p** [comment]
@samj1912 As suggested by the OP's inclusion of `--add-select` in #461, it appears that D417 is still excluded when `convention=numpy`. Same on my end - should this exclusion be removed? 

On the same topic, should the exclusion of D413 be removed for NumPy docstrings, as well? Everything I've seen on NumPy docstring style suggests that a blank line before closing the string is standard.
