### ISSUE TITLE
Pypi version publish request with latest features

### ISSUE THREAD

**Issue by ljades** [PyCQA/pydocstyle#405]
The extension of missing argument detection with Google-style docstrings is super helpful. When might we expect a new version on Pypi?

**Comment by samj1912** [comment]
@Nurdok can we do this please?

**Comment by samj1912** [comment]
@Nurdok any updates?

**Comment by Nurdok** [comment]
Sorry for the long delays in response - I've been on back-to-back family vacation and business trips. I'll to catch up as soon as I can.

There's a series of incoming PRs right now. I'll try to triage which ones can make it into a new version, but I think it'll probably take 2-3 weeks until we release a new version. Not sure. Will update this thread.

**Comment by Nurdok** [comment]
@ljades @samj1912 pydocstyle 5.0.0 is out!

**Comment by samj1912** [comment]
Wohoo! :D
