### ISSUE TITLE
Add support for autofixing some of the issues

### ISSUE THREAD

**Issue by samj1912** [PyCQA/pydocstyle#416]
It would be amazing if pydocstyle adds support for an --autofix flag.

I have started a python project to fix google style docstrings, but if there is interest I am willing to extend it to others.

If there's approval of such a feature in pydocstyle, I am also willing to merge https://github.com/samj1912/pygmend to pydocstyle.

**Comment by samj1912** [comment]
Duplicate of #249

**Comment by monim67** [comment]
This feature would be really great. Any update on this?
