### ISSUE TITLE
Wrong “D103: Missing docstring in public function” for overload functions

### ISSUE THREAD

**Issue by raabf** [PyCQA/pydocstyle#419]
For example:

```python
from typing import overload

@overload
def func(a: int) -> str:
     ...
@overload
def func(a: str) -> str:
     ...
def func(a):
     """Foo bar documentation."""
     return str(a)
```

will result in 

```
/home/raabf/Dokumente/overload_test.py:4 in public function `func`:
    D103: Missing docstring in public function
/home/raabf/Dokumente/overload_test.py:7 in public function `func`:
    D103: Missing docstring in public function
```

Which is wrong since only the last def should have a docstring.

Two things should be done:

First, prevent the error D103 for overload functions. We could make use of the `--ignore-decorators='overload'`, but since it is universally valid, it should be a fixed part of it, and the user should not set it by himself.

Second, since `@overload` functions should never have docstrings, it would be useful if there is an additional error code in pydocstyle, if someone is setting a docstring for an `@overload` function.

**Comment by Nurdok** [comment]
Both ideas sound good to me. PRs welcome.

**Comment by rmorshea** [comment]
This is a big issue for anyone using type annotations since turning off the error prevents you from ensuring you have documentation coverage. Given this drawback, @Nurdok, I think this is of slightly higher priority.

**Comment by rmorshea** [comment]
I've just noticed that you only have two priority tags so maybe this doesn't rise to the level of "major", but it's worth considering that turning off the error negates the huge benefit of guaranteeing doc coverage.

**Comment by thomasgilgenast** [comment]
I am also encountering this.

Instead of turning off D103 completely, I think it's possible to add `# noqa: D103` to the `@overload` definitions (but not the real implementation) as a temporary workaround.

**Comment by theyuvalraz** [comment]
I maybe biting more than I can chew. But I think I will take a stab at this.

If I understand correctly what is needed here is:
1. D103 shouldn't be triggered if the function is decorated with @overload.
2. If a function is decorated with @overload and has a docstring then it should throw a new error code.

**Comment by theyuvalraz** [comment]
@samj1912 
About the second objective: Adding a new error code for "Function decorated with @overload shouldn't contain a docstring"

This does not fit any of the grouping available, Should I create D5XX "shouldn't contain docstring" group?

**Comment by samj1912** [comment]
I think D4xx may still be a good candidate for this error

**Comment by jdtzmn** [comment]
Is this also fixed for D102? I'm still getting D102 errors on overloaded functions.

**Comment by ShadowLNC** [comment]
I'm not seeing D418 errors with the following file:

```
"""Reproduce D418."""

from typing import overload, Any

@overload
def func(val: str) -> str:
    ...

@overload
def func(val: int) -> int:
    """Return original value."""
    ...

def func(val: Any) -> Any:
    """Return original value."""
    return val
```

Should I be expecting to see them? `pydocstyle --version` gives 6.0.0.
