### ISSUE TITLE
--ignore-decorators does not work for one-line functions

### ISSUE THREAD

**Issue by raabf** [PyCQA/pydocstyle#420]
For example:

```python
def foodecorator(func):
     """Noop decorator."""
     return func

@foodecorator
def func(): return 42
```

And `pydocstyle --ignore-decorators='foodecorator' ~/Dokumente/one_line_test.py` on that file would result in:

```
/home/raabf/Dokumente/one_line_test.py:6 in public function `func`:
    D103: Missing docstring in public function
```

One-line functions are syntactically correct, but D103 is still printed although that function should be ignored by `--ignore-decorators='foodecorator'`.

**Comment by samj1912** [comment]
Should probably be fixed by https://github.com/PyCQA/pydocstyle/pull/411

**Comment by theyuvalraz** [comment]
#499 Is adding a test for this issue.

**Comment by samj1912** [comment]
fixed by https://github.com/PyCQA/pydocstyle/pull/499

**Comment by raabf** [comment]
Awesome, thank you for your work guys!
