### ISSUE TITLE
Add option to ignore specific errors per module

### ISSUE THREAD

**Issue by tpazderka** [PyCQA/pydocstyle#439]
It would be nice to be able to skip certain errors per module.

For example, I do want to force existence of docstrings in my projects (D1 is not ignored), but I only want to enforce format but not existence of docstrings in tests (ignore D1).

It could be similar to [isort](https://github.com/timothycrosley/isort#skip-processing-of-imports-outside-of-configuration) way of doing it. Add an option in module docstring.

**Comment by Nurdok** [comment]
This is already possible. If you put a config file in any subdirectory of your project, those settings will be applied to all files in that subdirectory.
See http://www.pydocstyle.org/en/5.0.1/usage.html#configuration-files
