### ISSUE TITLE
Colored terminal output

### ISSUE THREAD

**Issue by timhoffm** [PyCQA/pydocstyle#442]
The filename, line numbers and function are hard to read in the command line output, e.g.

~~~
lib/matplotlib/patches.py:3887 in public method `__init__`:
        D301: Use r""" if any backslashes in a docstring
lib/matplotlib/offsetbox.py:238 in public method `set_offset`:
        D301: Use r""" if any backslashes in a docstring
lib/matplotlib/image.py:741 in private method `set_interpolation`:
        D301: Use r""" if any backslashes in a docstring
~~~

It would be great to color them differently. I would be willing to provide a PR if there is interest.

If so:
- Should color be on or off by default?
- I'd use https://pypi.org/project/colorama/ for the output. Can I make it a dependency (hard or optional)?

**Comment by sigmavirus24** [comment]
Flake8 has a plugin that will color these for you and is configurable. FWIW

**Comment by timhoffm** [comment]
Thanks https://pypi.org/project/flake8-colors/ will do.

If somebody else want's to do this, you also need https://pypi.org/project/flake8-docstrings/ to make pydocstyle error codes available in flake8.
