### ISSUE TITLE
Rules D203 and D211 are conflicting

### ISSUE THREAD

**Issue by fkromer** [PyCQA/pydocstyle#474]
```python
class Something:

    """Some docstring.""""
    
    ...

```

leads to "No blank lines allowed before class docstring (found 1) pydocstyle(D211)". But

```python
class Something:
    """Some docstring.""""

    ...
```

leads to "1 blank line required before class docstring (found 0) pydocstyle(D203)". Obviously these rules are conflicting and it's worth a note that pydocstyle is not usable out-of-the-box but requires configuration (ignoring at least one of these two rules).

**Comment by samj1912** [comment]
Again see my reply at - https://github.com/PyCQA/pydocstyle/issues/475#issuecomment-627520864
