### ISSUE TITLE
 Rules D212 and D213 are conflicting

### ISSUE THREAD

**Issue by fkromer** [PyCQA/pydocstyle#475]
```python
"""Summary.

Extensive docs.
"""
```
leads to "Multi-line docstring summary should start at the second line pydocstyle(D213)".

```python
"""
Summary.

Extensive docs.
"""
```

leads to "Multi-line docstring summary should start at the first line pydocstyle(D212)".

Obviously these rules are conflicting and it's worth a note that pydocstyle is not usable out-of-the-box but requires configuration (ignoring at least one of these two rules).

**Comment by samj1912** [comment]
This seems incorrect. By default pydocstyle uses the pep257 configuration which explicitly ignore the two rules. See http://www.pydocstyle.org/en/5.0.1/usage.html#cli-usage and 

>  Only one of --select, --ignore or --convention can be specified. If
    none is specified, defaults to `--convention=pep257`.

And 

http://www.pydocstyle.org/en/5.0.1/error_codes.html#default-conventions

> The pep257 convention, which is enabled by default in pydocstyle, checks for all of the above errors except for D203, **D212, D213**, D214, D215, D404, D405, D406, D407, D408, D409, D410, D411, D413, D415, D416 and D417 (as specified in PEP257).
