### ISSUE TITLE
Sphinx compatibility?

### ISSUE THREAD

**Issue by fkromer** [PyCQA/pydocstyle#476]
`pydocstyle` needs to be configured w.r.t. alternative rules. Refer e.g. to https://github.com/PyCQA/pydocstyle/issues/475 and https://github.com/PyCQA/pydocstyle/issues/474 . I wondered if pydocstyle checked docstrings are compatible with [Sphinx](https://www.sphinx-doc.org/en/master/) with all possible configurations. Do I have to consider something w.r.t. Sphinx compatibility.

**Comment by samj1912** [comment]
pydocstyle is compatible with sphinx and I use it often with the napoleon extension

**Comment by fkromer** [comment]
Nice. And it's compatible independent on which rules are chosen? I like the docstring flavors (numpy, google) provided by napoleon as well. Could you provide your `pydocstyle` config? I don't want to waste time with a config which does potentially not play well with it.

**Comment by fkromer** [comment]
You are using `--convention=google` or `--convention=numpy` I guess?

**Comment by samj1912** [comment]
Yes, I use the Google convention.

**Comment by sigmavirus24** [comment]
And I use it with the regular plain ole Sphinx style of docstrings. Works great
