### ISSUE TITLE
D212 with a shebang line

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pydocstyle#483]
I'm getting a D212 error when I have a module docstring below the shebang line. Obviously, the module docstring should not be the first line when there is a shebang line (or an encoding line).

```
#!/usr/bin/env python3

"""
...
"""
```

I'm struggling to find any documentation that suggests whether there should be a blank line between or not, but the docstring is correctly picked up by Python with a blank line as shown above.

**Comment by theyuvalraz** [comment]
This error is legit in this situation(not related to the shebang line).
the D212 error is: Multi-line docstring summary should start at the first line. 
Which is from the google convention: https://google.github.io/styleguide/pyguide.html#382-modules

By this convention the summary line needs to start right after the """ without a newline. 
And should look like that:

```
"""A one line summary.

After one newline should be the description of the module.
"""
```

If you want to not get this error you can configure another (less rigid) convention.

**Comment by Dreamsorcerer** [comment]
I think you've misinterpreted that. From the same guide: https://google.github.io/styleguide/pyguide.html#37-shebang-line

> Start the main file of a program with #!/usr/bin/python

Both sections say something like "start the file with".

The question of whether the shebang or the docstring goes first is done to technical requirements. If the shebang is not the first line, the shell will not know what to do with the file. If the docstring is placed below the shebang, Python will still parse it as the module docstring.

While the styleguide doesn't explicitly spell this out for you, I think it's pretty obvious what the desired behaviour is.

**Comment by Dreamsorcerer** [comment]
Nevermind, I misinterpreted you're comment. Thanks for pointing that out.
