### ISSUE TITLE
No source package for 5.1.0

### ISSUE THREAD

**Issue by AMDmi3** [PyCQA/pydocstyle#503]
5.1.0 lacks source package on PyPI:

https://pypi.org/project/pydocstyle/5.1.0/#files

Compare to 5.0.2:

https://pypi.org/project/pydocstyle/5.0.2/#files

**Comment by samj1912** [comment]
Ack. Will fix

**Comment by samj1912** [comment]
https://pypi.org/project/pydocstyle/5.1.0/#files Fixed.
