### ISSUE TITLE
Add possibility to read config from .flake8

### ISSUE THREAD

**Issue by okainov** [PyCQA/pydocstyle#522]
I believe, a lot of people use the tool in combination with flake8. It would be great it it would be able to read settings not only from `.pydocstyle` file, but from `.flake8` as well. It's the same "ini", so it should be really easy...

**Comment by sigmavirus24** [comment]
> I believe, a lot of people use the tool in combination with flake8

As in using with `flake8-docstrings`? The options pydocstyle implements are pretty close to what flake8 uses so you don't need separate configuration for the tools if you use the plugin

**Comment by heoga** [comment]
Why not use setup.cfg and put the configuration of both in there if you want to consolidate?

**Comment by okainov** [comment]
>Why not use setup.cfg and put the configuration of both in there if you want to consolidate?

I think that's what we ended up doing, right. But my thought was as `pydocstyle` is somehow part of flake8 (at least, perceived so by users), it would make sense to read config from the same file as flake8...

**Comment by sigmavirus24** [comment]
> But my thought was as `pydocstyle` is somehow part of flake8 (at least, perceived so by users), it would make sense to read config from the same file as flake8.

It's not part of Flake8. You can plug it into Flake8 using `flake8-docstrings` which then _does_ receive config from `.flake8` in the `[flake8]` section passed into it from Flake8. It's also wholly separate and doesn't require Flake8. Flake8 can also read everything from `setup.cfg` , `tox.ini`, or `.flake8` and I believe 2 of those are supported by `pydocstyle`. There are options here (one of which is to not use pydocstyle directly but to use it with flake8-docstrings, another is to run separately and keep all your config options in one file supported by both tools, and I'm sure there are others).
