### ISSUE TITLE
Call for maintainers 

### ISSUE THREAD

**Issue by samj1912** [PyCQA/pydocstyle#575]
Hello all,

As of late, I have been the only somewhat active maintainer for pydocstyle and I am in a position where I am finding less and less time to dedicate to this project.

As a consequence, @Nurdok and I have decided to do a call for maintainers.

Ideally we would love for the new maintainer to

- be an avid user or contributor to pydocstyle or a similar project (like sibling linting projects in PyCQA)
-  have a good history of involvement in open source 

The immediate tasks for new maintainer(s) would be to - 

- Automate the release process 
- Release the current set of contributions on the master branch
- Triage the issue backlog
- Review the current set of open PRs 

Longer term, there are a few milestones on - 

- Making conventions a first class concepts in pydocstyle as opposed to a group of issues 
- Enhance the linting capabilities for numpy and Google docstyles 

for more details see https://github.com/PyCQA/pydocstyle/milestone/7

If you are interested, feel free to reach out to us on the pydocstyle #general discord channel https://discord.gg/GAt2YQEXga or comment on this issue.

**Comment by Pierre-Sassoulas** [comment]
Hello @samj1912, 

First, did you consider Tidelift ? [The current estimated income is 15$/month](https://tidelift.com/lifter/search/pypi/pydocstyle), it's not much, but it could justify spending an hour on it per month. 

Second I'm maintaining pylint, and pylint is not using pydocstyle directly but often have check that are very close or even duplicate (we handle numpy/google docstyle in our docstring plugin). Knowing pydocstyle better could be a way to rationalize pylint and maybe use pydocstyle directly inside it. Maybe a way to decrease the maintenance required for both.

I'm not saying I'd have the time to triage everything and review all the PR but I can at least automate the release process and release periodically because I already did that for pylint/astroid/prospector so it's... probably not much than copy pasting yaml in ``.git`` and asking you for the proper rights on pypi or defining an env variable in the github settings.

Let me know what you think :)

**Comment by samj1912** [comment]
@Pierre-Sassoulas that sounds great! I am away on vacations for the next few weeks so I might be slow to respond but if you send over a github actions PR, I can make sure proper secrets are injected in the workflows. 

I have not considered Tidelift. Thank you for the link, I will take a look :) I don't think that will massively change much, with regards to the current time I have available for pydocstyle.

**Comment by samj1912** [comment]
@aphedges has also graciously volunteered to help out with the triage and review process. I have added them with `triage` permissions to the repository to help with issue and PR reviews. Thanks for your help.

@saroad2 will message you separately :)

**Comment by saroad2** [comment]
@samj1912 , Have you sent me an email? cause I didn't get it.

**Comment by benji-york** [comment]
I've used pydocstyle on several projects over the last few years and have some time and interest to put into this project.  In fact, I just contributed my first PR—#595.

I have been involved with open source for nearly 20 years as both a maintainer and contributor on [many](https://pypi.org/user/benji/) projects.

**Comment by Stannislav** [comment]
Hi, I'd be happy to help as well.

I've been coding in python professionally for a number of years, and I've also contributed to open source before. I've used `pydocstyle` through the `flake8-docstrings` plugin a lot.

**Comment by adamjstewart** [comment]
We've been using pydocstyle in [TorchGeo](https://github.com/microsoft/torchgeo) for the last couple of years and absolutely love it. I would be interested in helping to maintain pydocstyle. I'm particularly interested in solving overloading (#525, #555, #571, #577, #601, #613) and Google-style docstring support (#459, #589) as these are the main bugs that impact us. I can also provide advice on CI/release procedures. I don't have a ton of time to offer, and I'm not yet familiar with the internals of the project, but if people can point me to where to start I'm happy to help. Thanks for building the most underrated and underappreciated style tool in existence!

**Comment by Pierre-Sassoulas** [comment]
@adamjstewart regarding the CI, you could review https://github.com/PyCQA/pydocstyle/pull/582 for the release process :)

**Comment by samj1912** [comment]
@adamjstewart, @Pierre-Sassoulas thank you so much for your contributions and interest.

Now that we have release automation in place and the current set of pending changes have been released, I think we are good to go WRT looking at the outstanding PRs and merging new functionality. 

I think a good starter PR would be related to the functionality you have pointed to (overloading and Google docstyle fixes), as they were next on the release map. 


Additionally if you wish to get familiar with the CI/CD process, having python 3.11 tests working would be awesome and would help unlock new functionality for us.

**Comment by samj1912** [comment]
Locking this thread for now since we have a good number of people interested in the maintanance.

@Pierre-Sassoulas given you are a pycqa admin, I'm more than happy to add you as a maintainer. 

@adamjstewart I have given you triage permissions. Happy to elevate them once you have reviewed/contributed a couple of PRs.
