### ISSUE TITLE
Handling of __init__.py Appears Incorrect

### ISSUE THREAD

**Issue by utkonos** [PyCQA/pydocstyle#593]
I am seeing D104 errors on `__init__.py`.

```
./src/example/__init__.py:1 at module level:
        D104: Missing docstring in public package
./src/example/templates/__init__.py:1 at module level:
        D104: Missing docstring in public package
```

Version of pydocstyle: `6.1.1`

**Comment by sigmavirus24** [comment]
Why does this appear incorrect to you?

**Comment by utkonos** [comment]
The more recent versions of pydocstyle are aware of `__init__.py`. I have no config settings, so it should go to the default and print `D107`. That code I can then add to an ignore line in the config. But I'm checking everything using the defaults first and found this error returned.

Am I mistaken about how pydocstyle should work in this case? If I am mistaken, under what conditions would a `D107` be printed?

**Comment by utkonos** [comment]
Forgive me, I see that there is a differentiation between public module and public package with public package **being** `__init__.py`.
