### ISSUE TITLE
Also allow other toml file readers

### ISSUE THREAD

**Issue by q-wertz** [PyCQA/pydocstyle#599]
Currently when the library `toml` is missing pydocstyle cannot read the `pyproject.toml` file.

It would be nice if also other toml reader would be supported ([`tomli`](https://pypi.org/project/tomli/)), resp. with python 3.11 the built in [`tomllib`](https://docs.python.org/3.11/library/tomllib.html) library (which is based on `tomli` as far as I know).

**Comment by adamjstewart** [comment]
Would be better to migrate to [tomli](https://pypi.org/project/tomli/) since the [tomllib](https://docs.python.org/3/library/tomllib.html) module introduced in Python 3.11 uses the same API.

Supporting multiple readers would increase maintenance overhead since they all have different APIs.
