### ISSUE TITLE
Need option to force return code of zero

### ISSUE THREAD

**Issue by pwm1234-sri** [PyCQA/pydocstyle#604]
I would like  pydocstyle to have an ``--exit-zero`` option when running as a pre-commit hook. 
I have a legacy code base that I would like pydocstyle to generate messages for but not fail the pre-commit. 
Flake8 has an ``--exit-zero`` option, but pydocstyle does not. 

Could you add an option similar to the flake8 ``--exit-zero`` so I can still use pydocstyle as a pre-commit hook without it failing the pre-commit check?

**Comment by pwm1234-sri** [comment]
I just came across the flake8-docstrings plugin. I think using pydocstrings through this flake8 plugin meets my goal. But being a newbie at pydocstring, flake8, and pre-commit, I would like to hear if this is the best approach.

Thanks!

**Comment by sigmavirus24** [comment]
It's the best approach to achieve this goal
