### ISSUE TITLE
Warning: Cannot parse file.

### ISSUE THREAD

**Issue by jlu-barracuda** [PyCQA/pydocstyle#628]
I have a Databricks style notebook with *.py extension, but contains ipython notebook magic commands like `%run` and `%pip install` that I believe is causing the parsing errors. I've added `# noqa` to end of these lines, however, I'm still getting the following error with termination in Github workflow. 

```
WARNING: Error in file EGD/egd_all_dlt.py: Cannot parse file.
Error: Process completed with exit code 1.
```

Is there a configuration to set to ignore file parsing errors?

**Comment by sigmavirus24** [comment]
pydocstyle uses the python standard ast library iirc and cannot parse ipynb because they're not python

There's no option to disable ast parsing

**Comment by jlu-barracuda** [comment]
thanks. I was able to get parsing working with ruff.
