### ISSUE TITLE
Docs website is down?

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/pydocstyle#641]
On 4/25/2023 at 2 pm pt at https://pydocstyle.org/en/stable/

![docs ERR_CONNECTION_TIMED_OUT](https://user-images.githubusercontent.com/8990777/234402410-b097ea5d-aa71-4da0-989c-5ec05a4b959a.png)

I think the website is down, it's giving a `ERR_CONNECTION_TIMED_OUT`

**Comment by sigmavirus24** [comment]
Duplicate #639
